In [3]:
# 1) Write a NumPy program to create an empty and a full array.(10 points)
import numpy as np

empty = np.empty((3, 4), dtype=int)
empty

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [4]:
full = np.full((4,3), 12, dtype=int)
full

array([[12, 12, 12],
       [12, 12, 12],
       [12, 12, 12],
       [12, 12, 12]])

In [10]:
# 2) Write a NumPy program to get the unique elements of an array.
original = np.array(['a', 'b', 'b', 'b', 2, 2, 3, 4, 1, 1, 1, 1, 1])
original

array(['a', 'b', 'b', 'b', '2', '2', '3', '4', '1', '1', '1', '1', '1'],
      dtype='<U11')

In [11]:
np.unique(original)

array(['1', '2', '3', '4', 'a', 'b'], dtype='<U11')

In [46]:
# 3) Write a NumPy program to construct an array by repeating
x = np.array([[1, 2, 3]])
np.repeat(x, 2)

array([1, 1, 2, 2, 3, 3])

In [47]:
np.tile(x, 2)

array([[1, 2, 3, 1, 2, 3]])

In [48]:
# 4) Write a NumPy program to sort pairs of first name and last name return their indices.
first_names = ("Betsey", "Shelley", "Lanell", "Genesis", "Margery")
last_names = ("Battle", "Brien", "Plotner", "Stahl", "Woolum")

z = np.lexsort((last_names, first_names))
z

array([0, 3, 2, 4, 1], dtype=int64)

In [49]:
# 5) Write a Python program to count number of occurrences of each value in a given array of non-negative integers.
given = np.array([0, 1, 6, 1, 4, 1, 2, 2, 7])

np.array(np.unique(given, return_counts=True)).T

array([[0, 1],
       [1, 3],
       [2, 2],
       [4, 1],
       [6, 1],
       [7, 1]], dtype=int64)

In [56]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter= ',' , dtype = 'object')
sepallength = np.genfromtxt(url, delimiter= ',', dtype = 'float', usecols =[0])

In [61]:
# 1) Find the mean, median, standard deviation of iris’s sepallength (1st column)
np.mean(sepallength)

5.843333333333334

In [62]:
np.median(sepallength)

5.8

In [64]:
np.std(sepallength)

0.8253012917851409

In [66]:
# 2) Find the 5th and 95th percentile of iris’s sepallength.
q95, q5 = np.percentile(x, [95, 5])
q95

2.9

In [67]:
q5

1.1

In [75]:
# 3) Create a normalized form of iris’s sepallength whose values range exactly between 0 and 1 
#so that the minimum has value 0 and maximum has value 1
Smax, Smin = sepallength.max(), sepallength.min()
S = (sepallength - Smin)/(Smax - Smin)

S

array([0.22222222, 0.16666667, 0.11111111, 0.08333333, 0.19444444,
       0.30555556, 0.08333333, 0.19444444, 0.02777778, 0.16666667,
       0.30555556, 0.13888889, 0.13888889, 0.        , 0.41666667,
       0.38888889, 0.30555556, 0.22222222, 0.38888889, 0.22222222,
       0.30555556, 0.22222222, 0.08333333, 0.22222222, 0.13888889,
       0.19444444, 0.19444444, 0.25      , 0.25      , 0.11111111,
       0.13888889, 0.30555556, 0.25      , 0.33333333, 0.16666667,
       0.19444444, 0.33333333, 0.16666667, 0.02777778, 0.22222222,
       0.19444444, 0.05555556, 0.02777778, 0.19444444, 0.22222222,
       0.13888889, 0.22222222, 0.08333333, 0.27777778, 0.19444444,
       0.75      , 0.58333333, 0.72222222, 0.33333333, 0.61111111,
       0.38888889, 0.55555556, 0.16666667, 0.63888889, 0.25      ,
       0.19444444, 0.44444444, 0.47222222, 0.5       , 0.36111111,
       0.66666667, 0.36111111, 0.41666667, 0.52777778, 0.36111111,
       0.44444444, 0.5       , 0.55555556, 0.5       , 0.58333

In [76]:
# 4) Filter the rows of iris that has petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0.
#https://pythontraining.dzone.co.in/tutorial/exercises/numpy/numpy-exercise_3.html
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

condition = (iris_2d[:, 2] > 1.5) & (iris_2d[:, 0] < 5.0)
iris_2d[condition]



array([[4.8, 3.4, 1.6, 0.2],
       [4.8, 3.4, 1.9, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [4.9, 2.4, 3.3, 1. ],
       [4.9, 2.5, 4.5, 1.7]])